# ./docker-compose-production.yml
version: '3'
services:
    app:
        container_name: emotion-map-backend
        image: hicsail/emotion-map-backend
        restart: always
        ports:
            - 3000:3000
        env_file:
            - ./stack.env
        depends_on:
            db:
                condition: service_healthy
    
    db:
        image: mysql:8.0
        container_name: emotions-map-mysql
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
