# ./docker-compose.yml
version: '3'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment: 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rsPASS1!
      - DB_SCHEMA=emotionmap
    depends_on:
      db:
          condition: service_healthy
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=rsPASS1!
      - MYSQL_DATABASE=emotionmap
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10