# ./docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment: 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rsPASS1!
      - DB_SCHEMA=emotionmap
    depends_on:
      db:
          condition: service_healthy
  db: 
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rsPASS1!
      - MYSQL_DATABASE=emotionmap
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10